# GitHub repository settings
# These settings are synced by the GitHub Settings app
# https://github.com/apps/settings

repository:
  name: assembly-notes
  description: Real-time transcription and meeting notes desktop app
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      # Required status checks
      required_status_checks:
        strict: true # Require branches to be up to date before merging
        contexts:
          - 'Build & Test / build (macos-latest, mac)'
          - 'Build & Test / build (ubuntu-latest, linux, x64)'
          - 'Build & Test / build (windows-latest, win)'

      # PR reviews - disabled for solo development
      required_pull_request_reviews: null

      # Enforces all configured restrictions for administrators
      enforce_admins: false

      # Prevents deletion of the protected branch
      allow_deletions: false

      # Allows force pushes to the protected branch
      allow_force_pushes: false

      # Requires all conversations to be resolved before merging
      required_conversation_resolution: false

      # Requires linear history
      required_linear_history: false

      # Restrictions on who can push
      restrictions: null

      # Allow bypass for specific apps/users (optional)
      bypass_pull_request_allowances:
        users: ['alexkroman', 'alexkroman-assembly']
        teams: []
        apps: []
