export const DI_TOKENS = {
  MainWindow: Symbol('MainWindow'),
  Store: Symbol('Store'),
  Logger: Symbol('Logger'),
  DatabaseService: Symbol('DatabaseService'),
  SettingsService: Symbol('SettingsService'),
  TranscriptionService: Symbol('TranscriptionService'),
  RecordingManager: Symbol('RecordingManager'),
  RecordingDataService: Symbol('RecordingDataService'),
  SlackIntegrationService: Symbol('SlackIntegrationService'),
  AutoUpdaterService: Symbol('AutoUpdaterService'),
  AssemblyAIFactory: Symbol('AssemblyAIFactory'),
  AssemblyAIFactoryWithLemur: Symbol('AssemblyAIFactoryWithLemur'),
  SummarizationService: Symbol('SummarizationService'),
  HttpClient: Symbol('HttpClient'),
  DictationService: Symbol('DictationService'),
  AudioRecordingService: Symbol('AudioRecordingService'),
  DictationStatusWindow: Symbol('DictationStatusWindow'),
} as const;
